force-app/main/default/objects/EmailQueue__c/EmailQueue__c.object-meta.xml
<CustomObject>
    <label>Email Queue</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Email Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailQueue__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>5 is highest</description>
    <inlineHelpText>5 is highest</inlineHelpText>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <label>Crucial</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Higher</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>High</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Medium</label>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/SaveAsActivity__c.field-meta.xml
<CustomField>
    <fullName>SaveAsActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</description>
    <inlineHelpText>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</inlineHelpText>
    <label>Save As Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Set to queued to queue email</description>
    <inlineHelpText>Set to queued to queue email</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Instant</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TargetObjectId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectId__c</fullName>
    <description
    >The ID for the Contact or Lead to receive the email</description>
    <inlineHelpText
    >The ID for the Contact or Lead to receive the email</inlineHelpText>
    <label>Target Object ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <description>The SObject EmailTemplate ID</description>
    <inlineHelpText>The SObject EmailTemplate ID</inlineHelpText>
    <label>Template ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueueSettings__c/EmailQueueSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Email Queue Settings</label>
</CustomObject>

force-app/main/default/objects/EmailQueueSettings__c/fields/AmountSentToday__c.field-meta.xml
<CustomField>
    <fullName>AmountSentToday__c</fullName>
    <label>AmountSentToday</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EmailQueueSettings__c/fields/ResetDate__c.field-meta.xml
<CustomField>
    <fullName>ResetDate__c</fullName>
    <label>ResetDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EmailQueueInstantSend_test.cls
@isTest
private without sharing class EmailQueueInstantSend_test {
	@isTest
	private static void testInsert() {

		EmailTemplate emailTemplate = new EmailTemplate( DeveloperName = 'MY_UNIQUE_TEMPLATE', Name = 'MY_UNIQUE_TEMPLATE', IsActive = true, FolderId = UserInfo.getOrganizationId(), UiType = 'sfx', TemplateType = 'custom', Subject = 'Test', HtmlValue = '<html><head></head><body><p>Hei {{{Recipient.Name}}}!.</p></body></html>' );
		insert emailTemplate;

		Contact con = new Contact( LastName = 'test', Email = 'test@test.com' );
		insert con;

		List<EmailQueue__c> emailQueues = new List<EmailQueue__c>();
		for ( Integer i = 0; i < 5; i++ ) {
			emailQueues.add( new EmailQueue__c( Priority__c = '1', SaveAsActivity__c = true, Status__c = 'Instant', TargetObjectId__c = con.Id, TemplateId__c = emailTemplate.Id ) );
		}

		Test.StartTest();
		insert emailQueues;
		Test.StopTest();

		System.assertEquals( 5, [SELECT Id FROM EmailMessage].size(), '5 emails sent after jobs' );
		System.assertEquals( 5, [SELECT Id FROM EmailQueue__c].size(), '5 emails in queue' );
		System.assertEquals( 5, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Sent'].size(), 'EmailQueue__c status should have been updated to "Sent"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Instant'].size(), 'no EmailQueue__c status should still be "Instant"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Queued'].size(), 'no more EmailQueue__c records with status "Queued"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Error'].size(), 'no EmailQueue__c records with status "Error"' );
	}

	@isTest
	private static void testUpdate() {

		EmailQueueData_test.createData( 5, null, true );   // create test data

		List<EmailQueue__c> emailQueue = [SELECT Id FROM EmailQueue__c];
		for ( EmailQueue__c queue : emailQueue ) {
			queue.Status__c = 'Instant';
		}


		Test.StartTest();
		update emailQueue;
		Test.StopTest();

		System.assertEquals( 5, [SELECT Id FROM EmailMessage].size(), '5 emails sent after jobs' );
		System.assertEquals( 5, [SELECT Id FROM EmailQueue__c].size(), '5 emails in queue' );
		System.assertEquals( 5, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Sent'].size(), 'EmailQueue__c status should have been updated to "Sent"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Instant'].size(), 'no EmailQueue__c status should still be "Instant"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Queued'].size(), 'no more EmailQueue__c records with status "Queued"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Error'].size(), 'no EmailQueue__c records with status "Error"' );
	}

	@isTest
	private static void testCap() {

		insert new EmailQueueSettings__c( AmountSentToday__c = 4995, ResetDate__c = Date.today() );
		EmailQueueData_test.createData( 15, null, true );

		List<EmailQueue__c> emailQueue = [SELECT Id FROM EmailQueue__c];
		for ( EmailQueue__c queue : emailQueue ) {
			queue.Status__c = 'Instant';
		}

		Test.StartTest();
		update emailQueue;
		Test.StopTest();

		System.assertEquals( 5, [SELECT Id FROM EmailMessage].size(), '5 emails sent after jobs' );
		System.assertEquals( 15, [SELECT Id FROM EmailQueue__c].size(), '5 emails in queue' );
		System.assertEquals( 5, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Sent'].size(), 'EmailQueue__c status should have been updated to "Sent"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Instant'].size(), 'no EmailQueue__c status should still be "Instant"' );
		System.assertEquals( 10, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Queued'].size(), 'no more EmailQueue__c records with status "Queued"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Error'].size(), 'no EmailQueue__c records with status "Error"' );

		List<EmailQueueSettings__c> settings = [SELECT Id, AmountSentToday__c FROM EmailQueueSettings__c WHERE LastModifiedDate = TODAY];
		System.assertEquals( 1, settings.size(), 'should be settings for today' );
		System.assertEquals( 5000, settings[0].AmountSentToday__c, 'should be settings for today' );
	}

	@isTest
	private static void testCap_exact5000() {

		insert new EmailQueueSettings__c( AmountSentToday__c = 4995, ResetDate__c = Date.today() );
		EmailQueueData_test.createData( 5, null, true );

		List<EmailQueue__c> emailQueue = [SELECT Id FROM EmailQueue__c];
		for ( EmailQueue__c queue : emailQueue ) {
			queue.Status__c = 'Instant';
		}

		Test.StartTest();
		update emailQueue;
		Test.StopTest();

		System.assertEquals( 5, [SELECT Id FROM EmailMessage].size(), '5 emails sent after jobs' );
		System.assertEquals( 5, [SELECT Id FROM EmailQueue__c].size(), '5 emails in queue' );
		System.assertEquals( 5, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Sent'].size(), 'EmailQueue__c status should have been updated to "Sent"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Instant'].size(), 'no EmailQueue__c status should still be "Instant"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Queued'].size(), 'no more EmailQueue__c records with status "Queued"' );
		System.assertEquals( 0, [SELECT Id FROM EmailQueue__c WHERE Status__c = 'Error'].size(), 'no EmailQueue__c records with status "Error"' );

		List<EmailQueueSettings__c> settings = [SELECT Id, AmountSentToday__c FROM EmailQueueSettings__c WHERE LastModifiedDate = TODAY];
		System.assertEquals( 1, settings.size(), 'should be settings for today' );
		System.assertEquals( 5000, settings[0].AmountSentToday__c, 'should be settings for today' );
	}
}