force-app/main/default/objects/EmailQueue__c/EmailQueue__c.object-meta.xml
<CustomObject>
    <label>Email Queue</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Email Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailQueue__c/fields/HTMLBody__c.field-meta.xml
<CustomField>
    <fullName>HTMLBody__c</fullName>
    <description>message HTML body, if not blank, uses instead of template</description>
    <label>HTML Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/SaveAsActivity__c.field-meta.xml
<CustomField>
    <fullName>SaveAsActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</description>
    <inlineHelpText>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</inlineHelpText>
    <label>Save As Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/ScheduledPriority__c.field-meta.xml
<CustomField>
    <fullName>ScheduledPriority__c</fullName>
    <description>Calculates when an emails should be scheduled to be sent (higher is sooner)</description>
    <formula>CASE( DaysSinceScheduled__c,

    0, VALUE(Text(Priority__c)) * (DaysSinceScheduled__c + 1),
    1, VALUE(Text(Priority__c)) * DaysSinceScheduled__c,
    2, VALUE(Text(Priority__c)) * DaysSinceScheduled__c * 2,
    3, VALUE(Text(Priority__c)) * DaysSinceScheduled__c * 2,

    10 * VALUE(Text(Priority__c)) * DaysSinceScheduled__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculates when an emails should be scheduled to be sent (higher is sooner)</inlineHelpText>
    <label>Scheduled Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Set to queued to queue email</description>
    <inlineHelpText>Set to queued to queue email</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Instant</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Sets subject if HTMLBody is not blank</description>
    <label>Subject</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TargetObjectId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectId__c</fullName>
    <description
    >The ID for the Contact or Lead to receive the email</description>
    <inlineHelpText
    >The ID for the Contact or Lead to receive the email</inlineHelpText>
    <label>Target Object ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <description>The SObject EmailTemplate ID</description>
    <inlineHelpText>The SObject EmailTemplate ID</inlineHelpText>
    <label>Template ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/ToAddress__c.field-meta.xml
<CustomField>
    <fullName>ToAddress__c</fullName>
    <description>Destination Email address</description>
    <label>To Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>The related SObject for the email. Required if the EmailTemplate contains lookup data content.</description>
    <inlineHelpText>The related SObject for the email. Required if the EmailTemplate contains lookup data content.</inlineHelpText>
    <label>What ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueueSettings__c/EmailQueueSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Email Queue Settings</label>
</CustomObject>

force-app/main/default/objects/EmailQueueSettings__c/fields/AmountSentToday__c.field-meta.xml
<CustomField>
    <fullName>AmountSentToday__c</fullName>
    <label>AmountSentToday</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmailQueueDataHelper.cls
public without sharing class EmailQueueDataHelper {
    private static final Integer MAX_AMOUNT_OF_EMAILS_PER_DAY = 5000; // 5000 is a Salesforce limit
    private static final Integer AMOUNT_OF_EMAILS_PER_BATCH = 100; // 100 email limit per batch
    private static final Integer AMOUNT_OF_BATCHES = 10; // can only call sendEmail 10 times
    private static final Integer MAX_EMAILS_PER_TRANSACTION = AMOUNT_OF_EMAILS_PER_BATCH * AMOUNT_OF_BATCHES;

    public static Integer calculateEmailLimit() {
        List<EmailQueueSettings__c> settings = [
            SELECT Id, AmountSentToday__c
            FROM EmailQueueSettings__c
            WHERE LastModifiedDate = TODAY
            ORDER BY AmountSentToday__c DESC
        ];

        Integer emailsSentToday = settings.size() == 0 ? 0 : Integer.valueOf(settings[0].AmountSentToday__c);
        Integer remainingEmailsToday = MAX_AMOUNT_OF_EMAILS_PER_DAY - emailsSentToday;

        // no more emails are allowed to be sent today, so query limit is zero
        if (remainingEmailsToday <= 0) {
            return 0;
        } else if (remainingEmailsToday < MAX_EMAILS_PER_TRANSACTION) {
            // the remaining emails allowed to be sent today is less than the transaction limit, so the remaining emails allowed becomes the query limit
            return remainingEmailsToday;
        } else {
            // the remaining emails allowed to be sent today is more than the transaction limit, so the transaction limit becomes the query limit
            return MAX_EMAILS_PER_TRANSACTION;
        }
    }

    public static List<EmailQueue__c> fetchEmailQueues(String status, Integer queryLimit) {
        return [
            SELECT SaveAsActivity__c, WhatId__c, TemplateId__c, TargetObjectId__c, ToAddress__c, HTMLBody__c, Subject__c, Id
            FROM EmailQueue__c
            WHERE Status__c = :status
            ORDER BY ScheduledPriority__c DESC NULLS LAST
            LIMIT :queryLimit
        ];
    }

    public static List<EmailQueue__c> fetchEmailQueues(List<EmailQueue__c> emailQueues, Integer queryLimit) {
        if (emailQueues.size() > queryLimit) {
            List<EmailQueue__c> toSend = new List<EmailQueue__c>();
            List<EmailQueue__c> toQueue = new List<EmailQueue__c>();

            for (Integer i = 0; i < queryLimit; i++) {
                toSend.add(emailQueues[i]);
            }
            for (Integer i = queryLimit; i < emailQueues.size(); i++) {
                toQueue.add(emailQueues[i]);
            }
            for (EmailQueue__c email : toQueue) {
                email.Status__c = 'Queued';
            }

            update toQueue;

            return toSend;
        } else {
            return emailQueues;
        }
    }

    public static List<List<EmailQueue__c>> separateEmailQueues(List<EmailQueue__c> emailQueues) {
        List<List<EmailQueue__c>> emailQueuesBatches = new List<List<EmailQueue__c>>();
        List<EmailQueue__c> emailQueuesSeparated = new List<EmailQueue__c>();
        Integer i = 1;

        if (emailQueues.size() == 0) {
            return emailQueuesBatches;
        }

        for (EmailQueue__c emailQueue : emailQueues) {
            emailQueuesSeparated.add(emailQueue);

            if (Math.mod(i, AMOUNT_OF_EMAILS_PER_BATCH) == 0) {
                emailQueuesBatches.add(emailQueuesSeparated);
                emailQueuesSeparated = new List<EmailQueue__c>();
            }

            i++;
        }

        if (Math.mod(i, AMOUNT_OF_EMAILS_PER_BATCH) != 0 && !emailQueuesSeparated.isEmpty()) {
            emailQueuesBatches.add(emailQueuesSeparated);
        }

        return emailQueuesBatches;
    }
}