force-app/main/default/objects/EmailQueue__c/EmailQueue__c.object-meta.xml
<CustomObject>
    <label>Email Queue</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Email Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailQueue__c/fields/HTMLBody__c.field-meta.xml
<CustomField>
    <fullName>HTMLBody__c</fullName>
    <description>message HTML body, if not blank, uses instead of template</description>
    <label>HTML Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/SaveAsActivity__c.field-meta.xml
<CustomField>
    <fullName>SaveAsActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</description>
    <inlineHelpText>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</inlineHelpText>
    <label>Save As Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Set to queued to queue email</description>
    <inlineHelpText>Set to queued to queue email</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Instant</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Sets subject if HTMLBody is not blank</description>
    <label>Subject</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TargetObjectId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectId__c</fullName>
    <description
    >The ID for the Contact or Lead to receive the email</description>
    <inlineHelpText
    >The ID for the Contact or Lead to receive the email</inlineHelpText>
    <label>Target Object ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <description>The SObject EmailTemplate ID</description>
    <inlineHelpText>The SObject EmailTemplate ID</inlineHelpText>
    <label>Template ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/ToAddress__c.field-meta.xml
<CustomField>
    <fullName>ToAddress__c</fullName>
    <description>Destination Email address</description>
    <label>To Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>The related SObject for the email. Required if the EmailTemplate contains lookup data content.</description>
    <inlineHelpText>The related SObject for the email. Required if the EmailTemplate contains lookup data content.</inlineHelpText>
    <label>What ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailQueueTrigger_sendInstant.cls
public inherited sharing class EmailQueueTrigger_sendInstant {
    public static void process(List<EmailQueue__c> emailQueue) {
        List<EmailQueue__c> filteredRecords = findInstantRecords(emailQueue);

        if (filteredRecords.size() > 0) {
            EmailQueueData data = new EmailQueueData(filteredRecords);

            for (List<EmailQueue__c> emailQueuesToSend : data.getEmailQueuesSeparated()) {
                Id jobId = System.enqueueJob(new EmailQueueJob(emailQueuesToSend, data.getOrgWideEmailId()));
            }

            EmailQueueJobHelper.updateEmailQueueSettings(data.getEmailQueues());
        }
    }

    public static List<EmailQueue__c> findInstantRecords(List<EmailQueue__c> emailQueue) {
        List<EmailQueue__c> filteredQueue = new List<EmailQueue__c>();

        for (EmailQueue__c queue : emailQueue) {
            if (queue.Status__c == 'Instant') {
                filteredQueue.add(queue);
            }
        }

        Set<Id> queueIds = new Map<Id, EmailQueue__c>(filteredQueue).keySet();

        return [
            SELECT SaveAsActivity__c, WhatId__c, TemplateId__c, TargetObjectId__c, ToAddress__c, HTMLBody__c, Subject__c, Id
            FROM EmailQueue__c
            WHERE Id IN :queueIds
        ];
    }
}