force-app/main/default/objects/EmailQueue__c/EmailQueue__c.object-meta.xml
<CustomObject>
    <label>Email Queue</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Email Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailQueue__c/fields/SaveAsActivity__c.field-meta.xml
<CustomField>
    <fullName>SaveAsActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</description>
    <inlineHelpText>EmailMessage SObject can automatically create a Task/Activity for the email for logging purposes and viewing if the email has been opened</inlineHelpText>
    <label>Save As Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Set to queued to queue email</description>
    <inlineHelpText>Set to queued to queue email</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Instant</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TargetObjectId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectId__c</fullName>
    <description
    >The ID for the Contact or Lead to receive the email</description>
    <inlineHelpText
    >The ID for the Contact or Lead to receive the email</inlineHelpText>
    <label>Target Object ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <description>The SObject EmailTemplate ID</description>
    <inlineHelpText>The SObject EmailTemplate ID</inlineHelpText>
    <label>Template ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>The related SObject for the email. Required if the EmailTemplate contains lookup data content.</description>
    <inlineHelpText>The related SObject for the email. Required if the EmailTemplate contains lookup data content.</inlineHelpText>
    <label>What ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailQueueJobHelper.cls
public with sharing class EmailQueueJobHelper {

	public static List<Messaging.SendEmailResult> sendEmail( List<EmailQueue__c> emailQueues, Id orgWideEmailId ) {

		List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
		for ( EmailQueue__c emailQueue : emailQueues ) {
			Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
			message.setWhatId(                  emailQueue.WhatId__c );
			message.setTemplateId(              emailQueue.TemplateId__c );
			message.setTargetObjectId(          emailQueue.TargetObjectId__c );
			message.setSaveAsActivity(          emailQueue.SaveAsActivity__c );
			message.setOrgWideEmailAddressId(   orgWideEmailId );
			messages.add( message );
		}

		return Messaging.sendEmail ( messages, false );
	}

	public static void updateEmailQueues( List<EmailQueue__c> emailQueues, List<Messaging.SendEmailResult> emailResults ) {

		if ( emailQueues.size() == emailResults.size() ) {

			for ( Integer i = 0; i < emailQueues.size(); i++ ) {

				if ( emailResults[i].isSuccess() ) {
					emailQueues[i].Status__c = 'Sent';
				}

				else {

					emailQueues[i].Status__c = 'Error';

					List<String> errorMsg = new List<String> ();
					for ( Messaging.SendEmailError error : emailResults[i].getErrors() ) {
						errorMsg.add( error.getStatusCode().name() );
						errorMsg.add( error.getMessage() );
						errorMsg.add( '' );
					}
					emailQueues[i].Error__c = String.join( errorMsg, '\n' );
				}
			}
		}

		// emailQueues and emailResults should always be the same, but handled just in case they're not
		else {

			List<String> emailQueueIds = new List<String>();
			for ( EmailQueue__c emailQueue : emailQueues ) {
				emailQueueIds.add( emailQueue.Id );
			}

			for ( EmailQueue__c emailQueue : emailQueues ) {
				emailQueue.Status__c = 'Error';
				emailQueue.Error__c = 'Some, all or no emails may have been sent. The amount of emailQueues and emailResults are different, so it\'s impossible to know which.\n\nThe other EmailQueue__c records that were in the same batch:\n' + String.join( emailQueueIds, '\n' );
			}
		}

		update emailQueues;
	}
}