force-app/main/default/objects/EmailQueue__c/EmailQueue__c.object-meta.xml
<CustomObject>
    <label>Email Queue</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Email Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Set to queued to queue email</description>
    <inlineHelpText>Set to queued to queue email</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Instant</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailQueueInstantSend.cls
public without sharing class EmailQueueInstantSend {

	public static void process( List<EmailQueue__c> emailQueue ) {
		List<EmailQueue__c> filteredQueue = new List<EmailQueue__c>();
		if ( filteredQueue.size() > 0 ) {

		}
	}

	public static List<EmailQueue__c> findInstantRecords( List<EmailQueue__c> emailQueue ) {

		List<EmailQueue__c> filteredQueue = new List<EmailQueue__c>();

		for ( EmailQueue__c queue : emailQueue ) {
			if ( queue.Status__c == 'Instant' ) {
				filteredQueue.add( queue );
			}
		}

		return filteredQueue;
	}
}