force-app/main/default/objects/EmailQueue__c/EmailQueue__c.object-meta.xml
<CustomObject>
    <label>Email Queue</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Email Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Set to queued to queue email</description>
    <inlineHelpText>Set to queued to queue email</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Instant</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TargetObjectId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectId__c</fullName>
    <description
    >The ID for the Contact or Lead to receive the email</description>
    <inlineHelpText
    >The ID for the Contact or Lead to receive the email</inlineHelpText>
    <label>Target Object ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailQueue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <description>The SObject EmailTemplate ID</description>
    <inlineHelpText>The SObject EmailTemplate ID</inlineHelpText>
    <label>Template ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailSchedulingLogHelper.cls
public with sharing class EmailSchedulingLogHelper {

	public static Map<Id, List<EmailQueue__c> > getEmailQueueSubjectAsKey( List<EmailQueue__c> emailQueue, Map<Id, String> templateSubjects ) {

		Map<Id, List<EmailQueue__c> > emailQueueIdAsKey = new Map<Id, List<EmailQueue__c> >();
		for ( EmailQueue__c email : emailQueue ) {
			if ( emailQueueIdAsKey.containsKey( email.TemplateId__c ) ) {
				emailQueueIdAsKey.get( email.TemplateId__c ).add( email );
			} else {
				emailQueueIdAsKey.put( email.TemplateId__c, new List<EmailQueue__c> { email } );
			}
		}

		return emailQueueIdAsKey;
	}

	public static List<EmailSchedulingLog.LogChildren> createChildren( List<EmailQueue__c> emailQueueChildren, Map<Id, String> contactNames ) {
		List<EmailSchedulingLog.LogChildren> children = new List<EmailSchedulingLog.LogChildren>();

		for ( EmailQueue__c email : emailQueueChildren ) {

			EmailSchedulingLog.LogChildren child = new EmailSchedulingLog.LogChildren();
			child.name = email.Id;

			child.label = contactNames.get( email.TargetObjectId__c );
			child.TargetObjectId = email.TargetObjectId__c;
			child.metatext = getStatus( email.Status__c );

			children.add( child );
		}

		return children;
	}

	public static String getStatus( String status ) {
		switch on status {
			when 'Sent' {
				return 'Sendt';
			} when 'Queued' {
				return '⏱ I utsendingskø';
			} when 'Instant' {
				return '⏱ Sendes straks';
			} when 'Error' {
				return '❌ Feilet ved utsending, kontakt en administrator';
			} when else {
				return status;
			}
		}
	}

	public static String getParentMetatext( List<EmailQueue__c> emailQueueChildren ) {

		for ( EmailQueue__c children : emailQueueChildren ) {
			switch on children.Status__c {
				when 'Queued' {
					return '⏱ I utsendingskø';
				} when 'Instant' {
					return '⏱ Sendes straks';
				} when 'Error' {
					return '❌ En eller flere e-poster feiler, klikk for mer informasjon';
				} when else {}
			}
		}

		Datetime d = emailQueueChildren[0].LastModifiedDate;

		return 'Sendt (' + d.day() + '.' + d.month() + '.' + d.year() + ')';
	}
}